{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "group", "query": "*" },
   { "name": "host", "query": "$group.*" },
   { "name": "application", "query": "$group.$host.*" },
   { "name": "items", "query": "$group.$host.$application.*" }
  ]
 },
 "panels": [
  {
   "title": "Hosts status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(1) as value,\r\n  (CASE status WHEN '1' THEN 'disabled' WHEN '0' THEN 'moniterd' ELSE 'unknow' END) as metric\r\nFROM hosts\r\nWHERE status in (0,1) and flags<>2\r\nGROUP BY status"
    }
   ]
  },
  { "title": "Panel Title", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 10, "x": 5, "y": 0 } },
  {
   "title": "CPU USAGE in %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "CPU user time" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk useage of /",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Usage of /boot",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 3 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": {
      "filter": "Free disk space on /boot (percentage)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Items status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(1) as value,\r\n  (CASE i.state WHEN '1' THEN 'problem' WHEN '0' THEN 'monited' ELSE 'unknow' END) as metric\r\nFROM items as i, hosts as h\r\nWHERE i.hostid=h.hostid and h.status =0 and h.flags<>2 and i.flags in (0,4) and i.status=0\r\nGROUP BY i.state"
    }
   ]
  },
  {
   "title": "Memory usage in %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "$group" },
     "host": { "filter": "$host" },
     "item": { "filter": "Available memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 7, "w": 10, "x": 5, "y": 8 },
   "targets": {
    "zabbix": {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   }
  },
  {
   "title": "Trigger status",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\r\n  now() as time_sec,\r\n  count(1) as value,\r\n  (CASE t.value WHEN '1' THEN 'Alert' WHEN '0' THEN 'Nomarl' ELSE 'unknow' END) as metric\r\nFROM hosts h,items i,functions f,triggers t\r\nWHERE  h.hostid=i.hostid and i.itemid=f.itemid and f.triggerid=t.triggerid and h.status =0 and h.flags<>2 and i.flags in (0,4) and t.flags in (0,4) and t.status=0 and i.status=0\r\nGROUP BY t.value"
    }
   ]
  }
 ]
}